version: '2'
services:
    nginx-wp:
        image:            "${IMG_NGINX}"
        container_name:   nginx-wp
        depends_on:
            - wp-app
        external_links:
            - wp-app:wordpress-app-fpm
        volumes:
            - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./docker/nginx/sites-enabled/wordpress.conf:/etc/nginx/conf.d/sites-enabled/wordpress.conf:ro"
        volumes_from:
            - wp-app:ro
        ports:
            - "80:80"
            - "443:443"
    wp-db:
        image:            "${IMG_MYSQL}"
        container_name:   wp-db
        hostname:         "${HOST_MYSQL}"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ${PATH_MYSQL_DATA}:/var/lib/mysql
    wp-app:
        image: "wp-app:latest"
        build:
            context:    ./docker/php/app
            dockerfile: Dockerfile
            args:
                BASE_WP_IMG: oleksiichernomaz/wordpress:${WP_VERSION}
        container_name:   wp-app
        hostname:         wp-app
        environment:
            - "DB_NAME=${MYSQL_DATABASE}"
            - "DB_USER=${MYSQL_USER}"
            - "DB_PASSWORD=${MYSQL_PASSWORD}"
            - "DB_HOST=${HOST_MYSQL}"
            - "DB_CHARSET=utf8"
            - "AUTH_KEY=${AUTH_KEY}"
            - "SECURE_AUTH_KEY=${SECURE_AUTH_KEY}"
            - "LOGGED_IN_KEY=${LOGGED_IN_KEY}"
            - "NONCE_KEY=${NONCE_KEY}"
            - "AUTH_SALT=${AUTH_SALT}"
            - "SECURE_AUTH_SALT=${SECURE_AUTH_SALT}"
            - "LOGGED_IN_SALT=${LOGGED_IN_SALT}"
            - "NONCE_SALT=${NONCE_SALT}"
            - "WP_DEBUG=${WP_DEBUG}"
            - "WP_TABLE_PREFIX=${WP_TABLE_PREFIX}"
        volumes:
            - ${PATH_LOGS}:/logs/
            #note, you can define WP uploads directory as volume, which is tracked by git or any vcs ;)
            #also, alternatively, you can plugins directory define as additional volume
            - ./data/wp-content/uploads:/www/wordpress.loc/wp-content/uploads
        depends_on:
            - wp-base
            - wp-db
        external_links:
            - "wp-db:${HOST_MYSQL}"
    #only used for building of base image, which you can pull from docker hub. When you copy docker-compose,
    #you, do not need this section
    wp-base:
        image: "oleksiichernomaz/wordpress:${WP_VERSION}"
        build:
            context:    ./docker/php/base
            dockerfile: Dockerfile
            args:
                WP_VERSION: ${WP_VERSION}
                BASE_IMG: ${PHP_BASE_IMG}
        container_name:   wp-base
